apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-0
  namespace: inspiring
spec:
  capacity:
    storage: 300Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/docker/volumes/mysql/data
  claimRef:
    namespace: inspiring
    name: mysql-data-mysql-0