apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: inspiring

resources:
  - secrets/mysql-secret.yaml
  - statefulsets/mysql-statefulset.yaml
  - services/mysql-service.yaml
  - pvs/mysql-pv.yaml